### ISSUE TITLE
Cambiar la parte de educación en el CV

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#105]
http://www.awesomescreenshot.com/image/1222818/eaf5c6c72e9022e040a43133302259c8

Aquí hay que tener en cuenta que hay gente que no terminó sus estudios.

De modo que sugiero quede de la siguiente manera:

1.- Escuela o institución
3.-  ¿Qué estudiaste?
4.- Nivel de estudios (Dropdown con: Primaria, Secundaria, Preparatoria, Estudios universitarios sin terminar, Técnico titulado, Estudios universitarios - no titulado, Estudios universitarios - titulado, Diplomado, Maestría, Doctorado
5.- Iniciaste en: mes/año. terminaste en: mes / año.

**Comment by Ganacontrol** [comment]
Estas loco. esto me tomaria mucho trabajo SI ES QUE sera posible.

Me opongo a hacer eso porque estos campos son opcionales, sino estudiaste no los llenas, sino acabaste entonces escribelo como una nota.
Yo no acabe mis estudios y se perfectamente que debo decirlo en la seccion de notas sino quiero mentir. 

Lo dejare abierto por si lo quieres discutir conmigo mas a fondo y convencerme.

**Comment by startupmax** [comment]
Ok entonces así:

Escuela o institución

Qué estudiaste

Fecha de inicio y fecha de finalización
