### ISSUE TITLE
Cambiar la parte de experiencia profesional en subir CV

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#106]
Le pondría:

¿En dónde?
Giro
Puesto
Comenzaste en: mes / año
Saliste en: mes / año
Una opción de checkmark que diga Trabajo actual y que inhabilite el "saliste en".
Un cuadro de texto que diga Actividades

**Comment by Ganacontrol** [comment]
No puedo hacer ningun cambio a esta sección, solo quitarla.

Asi como esta funciona bien, entiendo tus mejoras pero no son nada del otro mundo tampoco.  Y para personalizar esto necesitaria abrir el codigo en php y trabajarlo con un developer, no creo que valga la pena el esfuerzo para el reward de esto.

**Comment by startupmax** [comment]
Bueno, se puede hacer un renglón de fecha de inicio y otro de fecha de finalización? No supe como llenar ese donde preguntan ambas fechas en una sola linea de respuesta. 

Y otra cosa, en vez de notas puedes cambiarle a Actividades?

**Comment by Ganacontrol** [comment]
Por lo generalyo espero que  la gente lo llene "2001 - 2010".
No puedo poner dos campos separados para eso pero si puedo cambiarle de notas a actividades. Eso hare y cerrare este issue

**Comment by startupmax** [comment]
Ok
