### ISSUE TITLE
Muchos botones no parecen botones. Por ejemplo este de iniciar sesión.

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#108]
http://www.awesomescreenshot.com/image/1222859/b6d3f51966aa783fe3638498fc9faea3

**Comment by startupmax** [comment]
Yo le pondría Iniciar sesión. 

Con punto final.

**Comment by Ganacontrol** [comment]
Cuales otros te refieres? Ya puse el punto final, nose si pueda ponerlo como un boton dentro de ese recuadro, Podría ponerlo en negritas si eso te basta

**Comment by startupmax** [comment]
Sí, a eso me refiero. A que estén en color azul. O morado del color del logo. Pero que parezca un enlace.

**Comment by Ganacontrol** [comment]
Ya esta del color del logo todo ese mensaje incluyendo eso, no puedo cambiarle el color, quisieras Negritas o italic?

**Comment by Ganacontrol** [comment]
no se puede arreglar en este caso pero aviame si ves otros
