### ISSUE TITLE
Iniciar sesión como empleador?

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#109]
No entiendo, como vas a iniciar sesion usando botones sociales cuando le das click en iniciar sesión si todos los botones dicen iniciar sesion como candidato?

**Comment by Ganacontrol** [comment]
Si ya tienes una cuenta de empleador  y por alguna razon le das click en los botones de redes sociales Y LO TIENES VINCULADO, entonces iniciaras sesion como empleador, sino lo tienes vinculado, se creara una cuenta como candidato.

Fue pensado como una facilidad para candidatos, los empleadores no creo que les moleste iniciar sesion de manera normal, son empleadores...
