### ISSUE TITLE
Sueldo a la hora de publicar una oferta de trabajo

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#112]
Quitar el obligatorio del sueldo a la hora de publicar una oferta, no?

O en todo caso, que sea obligatorio pero agregar una casilla que diga ocultar sueldo. Así sigue funcionado la barrita esa para buscar trabajos de acuerdo al sueldo.

**Comment by Ganacontrol** [comment]
Esa barrita y su funcionamiento, es completamente normal, metete a otras bolsas de trabajo y vas a ver que al tratar de filtrar por salario empleos que no tienen salario, natural y correctamente no deben estar incluidos porque es gente que buscar empleos con salarios definidos.

Ya le quité el obligatorio
