### ISSUE TITLE
a la hora de previsualizar empleo

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#114]
http://www.awesomescreenshot.com/image/1222882/43cbb99575035b17528c3f477d15a131

cambiaría:

Editar publicación por editar oferta
Enviar esta oferta de empleo le pondría "Publicar oferta de empleo" Y ese botón lo pondría en verde para que lo encuentren rápido.

**Comment by Ganacontrol** [comment]
Ya hice los cambios de traducción, no puedo cambiar el color de ese boton.
