### ISSUE TITLE
página de Oferta enviada con éxito.

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#115]
Empleo Enviado con éxito. Su anuncio será visible una vez aprobado.

Yo pondría:

Oferta enviada con éxito. Su oferta será publicada a la brevedad, una vez aprobada por los administradores.

**Comment by Ganacontrol** [comment]
Ya quedó, excepto que no puedo cambiar "empleo" por "oferta" porque es la traducción standard para otros campos que tambien se ocupa aqui. Asi que el resultado final es.

Empleo enviado con éxito. Su oferta será publicada a la brevedad, una vez aprobada por los administradores.
