### ISSUE TITLE
Add logo and video background to homepage

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/ET2016#12]
There seems to be different margins (top / bottom) for menu, should the logo be aligned?  We may need to edit the logo source file to acommodate.

@startupmax  el theme no soporta un video background, si lo llegase a lograr poner - cada megabyte podria agregar mas de un segundo de load time así que sugiero que mejor usemos una imagen ya que el video podría afectar el load-time en celulares en especial.... y de preferencia una imagen que ocupe poco, menos de un mega si es posible.

**Comment by startupmax** [comment]
Revisar pixeleado del logo

**Comment by Ganacontrol** [comment]
https://www.empleostampico.com/wp-content/uploads/2016/02/logofinal.png
El logo por si solo tmb se ve pixeleado. 
El logo en el demo de workscout tambien se ve pixeleado, mandare un ticketde esto.

**Comment by Ganacontrol** [comment]
Podemos intentar dos cosas para arreglar el logo pixeleado:
a) Subir el archivo en la opcion para Retina del theme con el doble del tamaño actual del logo  (esta en 300x48, seria 600x96)
b) Subir el logo en el campo de retina como .SVG y ver que sucede.

ref: http://www.mightybytes.com/blog/make-retina-images-website/

**Comment by Ganacontrol** [comment]
Se me habia olvidado que el theme no soporta video background. Asi que empecemos con una imagen por ahora mientras le pregunto al autor y busco una solucion.

**Comment by Ganacontrol** [comment]
@startupmax  update de esto?
