### ISSUE TITLE
Mail CV aprobado.

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#124]
Hemos aprobado exitosamente tu currículum vitae en EmpleosTampico.com

Podrás verlo dentro de tu cuenta en la sección de currículums vitae.

Nuestra misión es encontrar la mejor oportunidad para ti de forma segura. Tu currículum será compartido solo con empleadores locales verificados buscando candidatos de tu perfil.

https://www.empleostampico.com/mi-cuenta

Muchas gracias,

El equpo de Empleos Tampico

DOS PREGUNTAS: 

1.- ¿Tienes que aprobar CV por CV como admin?
2.- ¿Le quitamos la parte en que dice que se compartirá con empleadores locales verificados? Mejor que diga en esa parte: Tu CV será compartido solamente con los empleadores locales que tu decidas al hacer click en el botón APLICAR.

**Comment by Ganacontrol** [comment]
El issue #125 tiene la conclusion de los quehaceres de este issue.
