### ISSUE TITLE
Sugiero esto para la parte de iniciar sesion de modo que está más facil de encontrar como hacer una cuenta de empleador o defierenciar una cuenta de otra

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#127]
¿Olvidaste tu contraseña? <- tipografia normal, alineado a la izquierda.
<espacio>
<espacio>
¿Aún no tienes una cuenta?  <- tipografía más grande y centrado
¡Regístrate aquí como candidato o empleador! <- tipografía más grande y centrado

**Comment by Ganacontrol** [comment]
Theme translations para meter el html necesario

**Comment by Ganacontrol** [comment]
No he podido hacer exactamente lo que pides pero ya hice algo, espero que con eso te sea suficiente
