### ISSUE TITLE
Quitar la regla de que la contraseña del usuario debe tener un signo de puntuación. En consecuencia, quitar el mensaje donde te solicita eso.

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#128]

**Comment by Ganacontrol** [comment]
Ya quité el "medidor de seguridad" pero no el mensaje, tener una contraseña débil ahora no los detendra de crear su cuenta, pero seguirá apareciendo - creo que es lo correcto para incentivar que hagan mejores contraseñas pero de ser necesario puedo esconder el mensaje. Creo que así esta mejor.
