### ISSUE TITLE
Borrar vinculación con Redes Sociales para la cuenta de empleadores

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#141]
Las cuentas de empleadores no se pueden vincular con redes sociales, así que no tiene sentido ese campo en la sección "Mi cuenta" de los empleadores.

**Comment by Ganacontrol** [comment]
Como que no pueden? Claro que pueden y sirve muy bien

**Comment by Ganacontrol** [comment]
Ya busque en la internet y no parece haber alguna solucion "oficial" para hacer este meollo con wp job manager,  Facebook no parece tener la flexibilidad para hacer esto como lo fantaseamos. Muchos optaron por ni siquiera usar el social login.  Despues de pensarle creo que hay tres alternativas viables...

Gratis:
Hacer all-in-one accounts, es decir, no hacer diferencia entre candidatos y empleadores, que todos tengan acceso a todo y naturalmente sera un solo social login para todos.

De paga, PROBABLEMENTE funcione bien, 14 USD/ Mes, este plugin me permitira asignar diferentes roles usando social login dependiendo de la pagina donde se encuentren, es decir, haria una pagina de registro para empleadores y quienes usen el social login via esa pagina seran empleadores y quien lo use en otro lado candidato:
http://codecanyon.net/item/userpro-user-profiles-with-social-login/5958681

Gratis:

Dejarlo como esta.

**Comment by Ganacontrol** [comment]
El consenso es hacer all-in-one accounts.
