### ISSUE TITLE
En la pagina publicar empleo:

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#151]
Borrar esto del primer campo: (Con este e-mail se registrará tu cuenta) (*)

Cambiar el nombre del campo Email de solicitud por E-mail de recepción de aplicaciones. 

En caso de poder ingresar más de un e-mail, incluir en la descripción:

A este e-mail llegarán las aplicaciones de los candidatos. Si incluyes más de uno, sepáralos con comas.

**Comment by Ganacontrol** [comment]
No se pueden poner varios emails, hay varios workarounds, como que ellos reenvien el correo a quien corresponda, 
Qzuias con ayuda de un programador podamos aceptar mas de un email pero nose si valga la pena y realment elo vayan a usar. Las empresas que se me ocurren que necesiten de esa funcionalidad seran las grandes, quienes tambien saben reenviar correos. Pero si, con ayuda de un developer quizas si podamos. No lo veo imposible.

**Comment by Ganacontrol** [comment]
Todo lo demas ya quedo
