### ISSUE TITLE
CV registrado repetido

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#157]
Al aplicar a un empleo la opción de CV registrado se repite. Opino que se debe borrar de arriba para que quede solo abajo.

**Comment by Ganacontrol** [comment]
No puedo mostrarles solo una opcion a quienes tengan el CV registrado, pero si puedo quitar una o la otra para ambos perfiles (sin cv registrado y con cv registrado).

Acabo de quitar la opcion de abajo, solo queda la de arriba para ambos.
