### ISSUE TITLE
Definir categorías

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#24]

**Comment by Ganacontrol** [comment]
ya las puse en la home, hay que darle una revsion para ver si podemos juntar alguna categoría y checar que estemos contentos con los iconos asignados a cada uno.

fyi: tmb puedes subir archivos aqui

**Comment by Ganacontrol** [comment]
1.- Cuales vamos a dejar en la home?
2.- Vamos a ponerle custom icons?
por ahora estoy usando los de https://fortawesome.github.io/Font-Awesome/icons/ porque la plantilla se integra con eso.

**Comment by startupmax** [comment]
podeos usar custom icons en los que no hayan quedado lógicos. déjame pasarte mi lista de cuales creo que deben quedar en home. los que mas van a buscar en Tampico, yo creo.

**Comment by Ganacontrol** [comment]
OK, de hecho solo tenemos que preocuparnos por asignarle iconos a esa lista porque los iconos solo apareceran en la home..
