### ISSUE TITLE
Hacer un SEO check manual y luego con Moz.

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/ET2016#26]
moz.com, esto requerira un free trial que necesita tarjeta $1 deposit. Con 30 días tengo para hacer todo lo que necesito como un seo ninja.

@startupmax necesito que entres a moz.com y empieces un free trial. Mi tarjeta de debito no la aceptó. Lo cancelare antes de los 30 días entonces no te cobraran los $100 que vale al mes pero también servira que lo veas para la agencia lo necesitaremos.

**Comment by startupmax** [comment]
te paso los datos de mi tarjeta o me pasas el link para el free trail?

**Comment by Ganacontrol** [comment]
Ya lo deje todo configurado y listo, el analisis estara listo en 1 semana.

**Comment by Ganacontrol** [comment]
Al parecer Moz no trabaja bien con cloudflare plus CDN, ya mande un ticket al soporte de moz para buscar una solucion ya que el bot de moz no esta detectando el https.

@startupmax  por favor reenviame la respuesta de moz, te llegara por email pronto.

**Comment by Ganacontrol** [comment]
El crawl test via API tambien fue fail. Quedan dos alternativas:
a) Desactivar cloudflare para efectuar el crawl.
b) Usar otro SEO crawler.

Voto por a) pero quiero esperar a recibir una respuesta a mi pregunta en el thread aver si hay algun workaround diferente.

**Comment by startupmax** [comment]
Creo que ya te contestaron. Te reenvié el mail. A ver si me puedes explicar en español mexicano, porfis. Porfitas.

**Comment by Ganacontrol** [comment]
Si ya lo vi, orita me encargo...

Basicamente Moz utiliza un bot para analizar los sitios web...
Ese bot, corre en una version de python (lenguaje de programacion) un poco antigua, que no soporta una medida de seguridad que tenemos implementada con Cloudflare (lo que pagamos via siteground para optimizar el codigo/velocidad de lapagina).
Resulta que hay (muchas) mas personas en la misma situación ya que Moz y cloudflare son muy populares.... y esta persona en el foto de Moz me esta ayudando porque el logró hacerlo funcionar...

**Comment by Ganacontrol** [comment]
@startupmax  ya hice lo que tenia que hacer... ahora te llegara un mail de moz con un archivo como el pasado - segun esto tarda unas horas, asi que para mañana ya te debio haber llegado a tu mail.

**Comment by Ganacontrol** [comment]
Este issue tiene como prerequisito resolver el #17 antes y lo acabo de reabrir.

**Comment by Ganacontrol** [comment]
Yoast hace esto se supone... pero todos estan raving sobre este plugin.. darle un vistazo
https://wordpress.org/plugins/google-sitemap-generator/

**Comment by Ganacontrol** [comment]
@startupmax ya cancelé Moz, no te cobrarán.
