### ISSUE TITLE
Cambios en "Menú de mi cuenta"

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#54]
Agregar los siguientes enlaces a la página de Mi cuenta, cada uno como un botón del menú que se encuentra en la columna del lado izquierdo de dicha página. 

"Mis favoritos"
"Mis aplicaciones" (sugiero cambiarle el nombre a Aplicaciones de empleo)
"Mis alertas"
"Subir Curriculum Vitae (sugiero cambiarle el nombre a Curriculum Vitae
-------------------

^^ Eso fue cancelado.

**Comment by Ganacontrol** [comment]
Mis aplicaciones, mis favoritos y la seccion de CV todo bien.

Mis alertas es fail al querer agregar una nueva alerta. Por alguna razon no funciona cuando lo pongo usando estos tabs.

**Comment by Ganacontrol** [comment]
Este issue se anula con el cambio de vuelta de mi cuenta al menu principal.
