### ISSUE TITLE
Pagina Publicar Empleo Título y Subtítulo

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#58]
Me parece repetitivo el título Escoger paquete y Selecciona un paquete. Yo dejaría nada más el título más grande, pero le pondría Selecciona un paquete.

**Comment by Ganacontrol** [comment]
No lo puse como sugieres pero checalo haber que opinas.

No puedo quitar el titulo de abajo porque cuando tienes un paquete comprado esa pantala muestra otra fila, la de tus paquetes ya comprados y la de los paquetes que puedes comprar.

Si agregas un paquete a tu cuenta y vuelves a esa pagina veras a lo que me refiero, de cualquier manera creo que como lo corregí se ve bien pero verificalo y sino te gusta reabre este issue.
