### ISSUE TITLE
Títutlo y descripción del paquete Promoción de apertura

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#59]
El título dice: Promoción de apertura - Gratis
Yo pondría: Promoción por apertura - Gratis

La descripción dice: ¡Gratis! para 3 empleos listados por 31 días.
Dice actualmente:
Publica empleos ilimitadamente y sin costo alguno. Agregar tal vez esta frase también: Cada empleo tendrá una vigencia de 31 días. 

Yo pondría:

**Comment by Ganacontrol** [comment]
tu pondrias.......................

**Comment by Ganacontrol** [comment]
Ya entendi, pero este campo no funciona así. 
Se forma por medio de varios strings. Es decir, no hay donde pueda cambiar este texto, agarra las palabras adecuadas de diferentes partes del  código. De forma que el formato de la descripción debe ser así:
#Precio para #empleos listados por #duracion
Se ajusta automaticamente segun la configuracion del paquete.

**Comment by Ganacontrol** [comment]
quitar la descripcionsino se puede cambiar bien

**Comment by Ganacontrol** [comment]
Ya le quité los signos de admiración y cambie listados por publicados.

Quiero recalcar que la sintaxis solamente está mal escrita por el asunto de que son gratis. De lo contrario estaría correcta ya que en vez de ilimitados diria "3" o el numero que asignemos a ese paquete.
