### ISSUE TITLE
Finish facebook app process for apply with facebook integration

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/ET2016#6]
https://wpjobmanager.com/document/apply-with-facebook/

**Comment by Ganacontrol** [comment]
Ya aregue el woocommerce social login, cabe destacar que cuesta 80 USD, lo consegui "entre mis archivos... y funciona perfectamente con una EXCEPCION.
@startupmax 
La excepcion es que normalmente en el proceso de registro, el usuario escoge si busca empleo o es empleador y se le auto-asigna el rol correspondiente.. 
Cuando usen el facebook login, automaticamente los vuelve candidatos, no funciona para empleadores y por el momento esto no tiene solución. 

Opcion a) Lo dejo asi. 
Opcion b) Quitamos el facebook login.

Hable ahora o calle para siempre.

**Comment by startupmax** [comment]
No hay pedo @Ganacontrol solo especificamos que es para candidatos. O el botón puede decir Registrarse como candidato usando mis credenciales de facebook. Si es que no está muy largo jaja

**Comment by Ganacontrol** [comment]
@startupmax  OK, si, esta largo, namas pongamonos, checa lo que puse por ahora y cuando sepamos el mensjae correcto, sea lo modificamos - seguro lo checaremos cuando veamos lo de traducciones
