### ISSUE TITLE
Quita del formulario de publicar empleo la opcion de extender la fecha de la vacante

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#62]

**Comment by Ganacontrol** [comment]
Me quedé pensando que este feature no es tanto para los empleadores... es para los candidatos.
Si no hay una fecha de cierre del empleo como saben los candidatos cual es la fecha limite para aplicar? Es decir... si el empleador tiene planeado dejar la vacante por 3 meses, pero en ningun campo lo establece... como saben los candidatos cuanto tiempo tienen para aplicar? Me fije en los portales de Irlanda y todos tienen la fecha de caducidad del empleo...

Creo que la deberiamos de dejar.... Quitarlo no es problema, namas es desinstalar el plugin que fue hecho especificamente para eso. 
https://wpjobmanager.com/add-ons/application-deadline/
