### ISSUE TITLE
Bug menu Macboook Pro (Retina 13 pulgadas, principios de 2015) 13.3 pulgadas (2560 x 1600)

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#88]

**Comment by Ganacontrol** [comment]
@startupmax  Que te parece si quito el boton de "Registro" a logged out users y tambien quito el -segundo- "Mi Cuenta" para logged in users? 
Propongo esto porque no he podido replicar el bug en mi browser ajustando el tamaño del browser y necesito poder replicar el problema para dar esa instruccion especifica en el codigo
