### ISSUE TITLE
Cambiar el mensaje de bienvenida a Mi Cuenta del candidato

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#94]
Bienvenido a tu cuenta. 

Aquí podrás editar tu currículum vitae, consultar tus aplicaciones de empleo, accesar a tus favoritos y establecer alertas para nuevas vacantes de tu interés. 

También puedes cambiar tu correo electrónico, contraseña y asociar tu cuenta a distintas redes sociales.

**Comment by startupmax** [comment]
Checa la descripción.

**Comment by Ganacontrol** [comment]
No puedo poner mensajes diferentes para cada perfil, el mensaje de mi cuenta debe ser el mismo para todos los roles.

**Comment by startupmax** [comment]
Ok, ya te puse el mensaje que pienso que quedaría bien en el otro issue de empleador
