### ISSUE TITLE
Cuando inicie sesión el empleador que inicie en Mi cuenta

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#96]

**Comment by Ganacontrol** [comment]
Lo probaste? asi funciona ahorita para mi

**Comment by startupmax** [comment]
Me sigue enviando a mis ofertas de empleo.

**Comment by Ganacontrol** [comment]
Ya mande un ticket al autor del theme para saber si el puso en el codigo algo de esto porque yo utilizo un plugin que funcionaba perfectamente y con la nueva version del theme me parece que el le movio a eso

**Comment by Ganacontrol** [comment]
Listo
