### ISSUE TITLE
Cambiar el mensaje de Bienvenida a mi cuenta del Empleador

### ISSUE THREAD

**Issue by startupmax** [Ganacontrol/ET2016#98]
Explora las nuevas secciones disponibles en el menú principal, aquí puedes editar tu cuenta y contraseña o asociarla con tus redes sociales.

**Comment by startupmax** [comment]
Bienvenido a tu cuenta. 

Aquí podrás editar tu editar tus ofertas de empleo y consultar quién ha aplicado a las mismas. 

También puedes cambiar tu correo electrónico, contraseña y asociar tu cuenta a distintas redes sociales.

**Comment by Ganacontrol** [comment]
No puedo poner mensajes diferentes de bienvenida a diferentes roles, debe ser el mismo.

**Comment by startupmax** [comment]
Bienvenido a tu cuenta. 

Te invitamos a explorar las funciones disponibles en el menú.

**Comment by startupmax** [comment]
asi, simplito.
